version: "3.8"

services:
  api:
    build: .
    container_name: pbmarket_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: pb_market_db
      DB_PORT: 5432
    restart: always

  postgres:
    image: postgres:16
    container_name: pbmarket_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: pb_market_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
